### ISSUE TITLE
EPIC: faq

### ISSUE THREAD

**Issue by jkrug** [ongr-io/docs.ongr.io#51]
We need to have an easy to maintain place where we answer questions / tutorials / ... can be collected and maybe answered; also by a growing community.

Examples:
- How to sort products by a boosting?
- How to search (boosted) through multiple fields?
- ...

**Comment by saimaz** [comment]
These particular questions are related to FilterManager and has to answered there. We cannot have defined topics in different places because there won't be any chance to update them whenever changes in the component. 

The only way to place it to a single place is to write a small application which coud collect the docs from the repositories and constantly sync it.

**Comment by jkrug** [comment]
These are examples. I disagree, that we should have the documentation in the bundles. I see that ONGR is ONE application by combining a bunch of bundles. When you are a beginner, you don't know where to start searching. So please don't hide these questions in different places.

**Comment by saimaz** [comment]
I agree that the docs from all our bundles has to be in a single place. That's why I'm working on a handbook version to collect it in a single place. You may ask why I do that, I searched for a toll, but sadly there wasn't that could fit to get functionality we need. As the final result we will have a searchable collected docs in a single, and there will be a version select. Currently any bundle can be released with different version. And if user wants to see what was before he should be able to select previous version.

I dissagree that ONGR is some one application. It's pure simple Symfony project that uses ONGR bundles. It's not a new framework or somth. I might be wrong because maybe I don't understand terms correctly. All topics has to be in its related bundle, otherwise it will be **HELL** to maintain it.

**Comment by saimaz** [comment]
Global tutorials, how's to can be written in https://github.com/ongr-io/global-docs, I created a separate repository to store only topics what is related with all ONGR bundles.
